### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by pinghsi** [hahamyt/ISTD#1]
It seems that there is something wrong with the variables "response" in the function "detect_threshold" 
 Thanks

**Comment by hahamyt** [comment]
> It seems that there is something wrong with the variables "response" in the function "detect_threshold"
> Thanks

Sorry to reply so late. I just see this issue today.

What the specific error message is?

It should be noticed that the 'error('XXX');' sentences should be commented out before you run the code.

**Comment by hahamyt** [comment]
> > It seems that there is something wrong with the variables "response" in the function "detect_threshold"
> > Thanks
> 
> Sorry to reply so late. I just see this issue today.
> 
> What the specific error message is?
> 
> It should be noticed that the 'error('XXX');' sentences should be commented out before you run the code.

These 'error('XXXX');' messages are adopted as a reminder for users where to set the parameters by themselves.

**Comment by pinghsi** [comment]
I have already commented the error('XXX') and another error comes out...
When I run ADDGD in "run_experiment", the warning shows that the matrix dimensions is not agree which cause by the variables "response"    Thanks!!

**Comment by hahamyt** [comment]
> I have already commented the error('XXX') and another error comes out...
> When I run ADDGD in "run_experiment", the warning shows that the matrix dimensions is not agree which cause by the variables "response" Thanks!!

Maybe you need to delete the results you obtained before (in ./results/), then relaunch the evaluation process.
